### ISSUE TITLE
Branch back to twig-drupal-filters?

### ISSUE THREAD

**Issue by RobLoach** [JohnAlbin/drupal-twig-extensions#13]
Hey John!

Saw you added a few awesome things here. Noticed you weren't a maintainer of the npm package so I added you there:
https://www.npmjs.com/package/twig-drupal-filters

Anyways, if you're up to move these changes back up to -filters, I'm sure they'd be happy to.

Thanks!
Rob

**Comment by JohnAlbin** [comment]
I originally planned to add all of these updates to twig-drupal-filters, but the project name is arguably wrong.

We have filters, functions and (eventually) tags. Not just filters. And those are all types of twig extensions.

That's why I decided to create a new project. I hope you understand.
