### ISSUE TITLE
Add dual support for CommonJS and ES Modules

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/drupal-twig-extensions#21]
We are currently distributing this packages as CommonJS files (compiled by Babel). To make distributing a dual CJS/ESM as easy as possible we should follow [Approach 2 of “Writing dual packages while avoiding or minimizing hazards”](https://nodejs.org/api/packages.html#approach-2-isolate-state).

* Update `package.json` to add a `"type": "module",`.
* Use Babel to transpile our ES .js files to .cjs files.
* Rename our `dist` folder to `commonjs` to make it obvious which files are which.
* Update our `main` entry to point at `dist/index.cjs`.
* Add `exports` in our `package.json` to support CJS and ESM.
* Drop support for Node.js v12. #20

**Comment by JohnAlbin** [comment]
Since we're dropping support for Node.js v12, Node.js v14 and later support native ES Modules. So… why do we actually need CommonJS files? Seems like we don't need them. Or Babel.

**Comment by JohnAlbin** [comment]
Since we're dropping support for Node.js v12, Node.js v14 and later support native ES Modules. So… why do we actually need CommonJS files? Seems like we don't need them. Or Babel.

**Comment by MichaelAllenWarner** [comment]
@JohnAlbin 

One reason to reconsider is that this change breaks Storybook support: https://github.com/storybookjs/storybook/issues/11587

(Just discovered this when I tried to upgrade from `1.0.0-alpha.6` to your new beta.)

P.S. Thanks for this Twing-compatible project.

**Comment by MichaelAllenWarner** [comment]
(I should add that I'm using Node 16 and the latest version of Storybook with its Webpack 5 option enabled.)

**Comment by JohnAlbin** [comment]
@MichaelAllenWarner The Storybook issue you mentioned is about _your_ project using `type: module` in its package.json, not about dependencies using it.

Regardless, I noticed that `1.0.0-beta.1` broke webpack 4 support. And fixed it in #39 which was released with `1.0.0-beta.3` last night. I haven't tested webpack 5 though.

If you are still experiencing this issue with `1.0.0-beta.3` and webpack 5, can you open a new issue? Thanks!

**Comment by JohnAlbin** [comment]
oh, lol! I marked this as `wontfix` because I ended up doing this instead: #22 

So definitely open a new issue if this bug persists with `1.0.0-beta.3`.
